default/objects/Stock__c/Stock__c.object-meta.xml
<CustomObject>
    <label>Stock</label>
    <nameField>
        <displayFormat>S-{0000}</displayFormat>
        <label>Stock Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Stock</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

default/objects/Stock__c/fields/Last_Rented_Date__c.field-meta.xml
<CustomField>
    <fullName>Last_Rented_Date__c</fullName>
    <label>Last Rented Date</label>
    <type>Date</type>
</CustomField>

default/classes/StockDateSetter.cls
public with sharing class StockDateSetter {
    
    public static void setLastRentedDateOnRental(List<Stock__c> updatedStock,
                                                    Map<Id, Stock__c> oldValueMap) {

        for(Stock__c s : updatedStock) {
            if(s.Status__c == 'Rented' &&
                oldValueMap.get(s.Id).Status__c != 'Rented') {

                s.Last_Rented_Date__c = Date.today();
            }
        }
    }
}